#!/bin/sh

[ ! -d "bin" ] && mkdir bin

gcc -o bin/generador generador.c \
    && gcc -o bin/main main.c \
    && compilacion/despachador \
    && compilacion/lectorProcesos \
    && compilacion/fifo
