#!/bin/sh

[ ! -d "bin" ] && mkdir bin

gcc -o bin/generador generador.c -Wall \
    && gcc -o bin/main main.c productorConsumidor.c semaforos.c utilerias.c -Wall \
    && compilacion/despachador \
    && compilacion/lectorProcesos \
    && compilacion/fifo \
    && compilacion/sjf \
    && compilacion/srtf
