#!/bin/sh

gcc -o bin/fifo-corto fifo.c ejecutor.c pipes.c utilerias.c \
    productorConsumidor.c semaforos.c listas.c despachador.c \
&& gcc -o bin/fifo-largo fifo.c receptor.c pipes.c utilerias.c \
    listas.c productorConsumidor.c semaforos.c despachador.c
