#!/bin/sh

gcc -o bin/sjf-corto sjf.c ordenamiento.c ejecutor.c pipes.c utilerias.c \
    productorConsumidor.c semaforos.c listas.c despachador.c memoria.c -Wall \
&& gcc -o bin/sjf-largo sjf.c ordenamiento.c receptor.c pipes.c utilerias.c \
    listas.c productorConsumidor.c semaforos.c despachador.c memoria.c -Wall
