#!/bin/sh

gcc -o bin/srtf-corto srtf.c ejecutor.c pipes.c utilerias.c \
    productorConsumidor.c semaforos.c listas.c despachador.c -Wall \
&& gcc -o bin/srtf-largo srtf.c receptor.c pipes.c utilerias.c \
    listas.c productorConsumidor.c semaforos.c despachador.c -Wall
